### ISSUE TITLE
Issue when recording

### ISSUE THREAD

**Issue by Levrden** [keijiro/AudioPreviewTrack#2]
Hi Keijiro
I'm sorry is this thread isn`t at its normal place,
I'm having an issue with the audio preview track in unity 2020, which looks like the descendant of your script
the issue i have is that i use a script to analyse the amplitude of a track, for audioreacting a value with it
But when i record it with the recorder, or with your ffmpeg recorder, with frame controller, the music is red at normal speed, but the timeline is not, because of the fps control, which of course, i need
So do you have any idea for a way to force the music to be played at the timeline's time ?

thanks, hope my question is clear

Jonathan

**Comment by keijiro** [comment]
I think you shouldn't use my outdated package like AudioPreviewTrack or FFmpegRecorder. As I noted on README, you can scrub audio tracks without installing this package. The latest version of the UnityRecorder supports extra codec like ProRes.

**Comment by Levrden** [comment]
yes, i guess your're right, even if sometimes i do prefer your recorder than unity's
But it is the same with unity's official packages, and i found nothing on the web about that, i thought maybe you'de have some idea
________________________________

**Comment by keijiro** [comment]
> maybe you'de have some idea

The short answer is no. I have never tried recording audio tracks via Unity Recorder, because I don't want to be troubled with those kinds of problems. I always use external video editing software to mix audio tracks.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
